// Generated by scripts/prepare-hero.mjs — do not edit by hand.
export const heroBlurDataURL =
  "data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAAAQBACdASoOABUAPt1ep00opSOiMAgBEBuJYgCdMoACtA+8jGR1WBkc4AD+o2gHTPIyruKPq6VXzGzsPr3dlLO500NFRGACYs4D2fSoSjm8Ei0DqcIM06ERosFbiCoXDDP85ggA";
