/**
 * Prepares the hero portrait: trims platform watermarks from the source frame,
 * applies a restrained base grade, and writes the optimised asset that
 * `components/hero/hero-portrait.tsx` consumes.
 *
 * Usage: node scripts/prepare-hero.mjs <source-image> [--out public/images/kartik-hero.jpg]
 *
 * The heavy cinematic treatment (contrast, carbon wash, edge dissolve) lives in
 * CSS so a replacement photograph inherits it automatically.
 */
import { argv } from "node:process";
import { writeFile } from "node:fs/promises";
import sharp from "sharp";

const source = argv[2];
if (!source) {
  console.error(
    "usage: node scripts/prepare-hero.mjs <source-image> [--out <path>]",
  );
  process.exit(1);
}
const outIndex = argv.indexOf("--out");
const out =
  outIndex === -1 ? "public/images/kartik-hero.jpg" : argv[outIndex + 1];

// Fractions of the frame removed to drop watermark overlays that sit in the
// top and bottom safe areas of phone-camera exports.
const TRIM_TOP = 0.072;
const TRIM_BOTTOM = 0.091;
const TARGET_WIDTH = 1240;

const image = sharp(source).rotate();
const { width, height } = await image.metadata();
if (!width || !height)
  throw new Error(`could not read dimensions of ${source}`);

const top = Math.round(height * TRIM_TOP);
const cropHeight = Math.round(height * (1 - TRIM_TOP - TRIM_BOTTOM));

const pipeline = sharp(source)
  .rotate()
  .extract({ left: 0, top, width, height: cropHeight })
  .resize({ width: TARGET_WIDTH, withoutEnlargement: true })
  .modulate({ saturation: 0.82, brightness: 0.97 })
  .linear(1.08, -10);

await pipeline.clone().jpeg({ quality: 88, mozjpeg: true }).toFile(out);

// Low-resolution placeholder so the portrait never pops in against carbon.
const blur = await pipeline
  .clone()
  .resize({ width: 14 })
  .blur(1)
  .webp({ quality: 45 })
  .toBuffer();

await writeFile(
  "app/hero-blur.ts",
  `// Generated by scripts/prepare-hero.mjs — do not edit by hand.\n` +
    `export const heroBlurDataURL =\n  "data:image/webp;base64,${blur.toString("base64")}";\n`,
);

/* A tighter 4:5 detail crop of the same frame, used in the About section so
   the page has a second visual anchor without reaching for stock imagery. */
const detailOut = out.replace(/kartik-hero/, "kartik-portrait");
const detail = await sharp(out).metadata();
if (detail.width && detail.height) {
  const detailWidth = Math.round(detail.width * 0.66);
  const detailHeight = Math.round(detailWidth * 1.25);
  await sharp(out)
    .extract({
      left: Math.round(detail.width * 0.19),
      top: Math.round(detail.height * 0.2),
      width: Math.min(detailWidth, detail.width),
      height: Math.min(detailHeight, detail.height),
    })
    .resize({ width: 900, withoutEnlargement: true })
    .jpeg({ quality: 88, mozjpeg: true })
    .toFile(detailOut);
  console.log(`wrote ${detailOut}`);
}

const result = await sharp(out).metadata();
console.log(`wrote ${out} (${result.width}x${result.height})`);
console.log("wrote app/hero-blur.ts");
